import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { extractTables } from '../src/extractors';

interface ExpectedTable {
  source: string;
  page: string;
  matrixRows: number;
  columns: number;
  businessRows: number;
  completeness: string;
  expectedBusinessRows?: number;
  requiredWarningCodes?: string[];
  matrix: string[][];
}

const root = resolve('manual-qa');
afterEach(() => { document.head.replaceChildren(); document.body.replaceChildren(); });

describe('independent manual QA fixtures', () => {
  it.each(['01-basic-table', '02-complex-table', '03-risk-table'])(
    '%s matches its independently authored expected matrix and scope', (name) => {
      const expected = JSON.parse(readFileSync(resolve(root, 'expected', `${name}.json`), 'utf8')) as ExpectedTable;
      const markup = readFileSync(resolve(root, 'pages', expected.page), 'utf8');
      const page = new DOMParser().parseFromString(markup, 'text/html');
      document.head.innerHTML = page.head.innerHTML;
      document.body.innerHTML = page.body.innerHTML;
      const { tables } = extractTables(document);
      expect(tables).toHaveLength(1);
      const candidate = tables[0]!;
      expect(candidate.rows).toEqual(expected.matrix);
      expect(candidate.rows).toHaveLength(expected.matrixRows);
      expect(candidate.columns).toBe(expected.columns);
      expect(candidate.diagnostics?.completeness).toBe(expected.completeness);
      expect(candidate.diagnostics?.extractedRows).toBe(expected.businessRows);
      if (expected.expectedBusinessRows !== undefined) {
        expect(candidate.diagnostics).toMatchObject({ extractedRows: 4, expectedRows: expected.expectedBusinessRows });
      }
      for (const code of expected.requiredWarningCodes ?? []) {
        expect(candidate.diagnostics?.warnings.map((warning) => warning.code)).toContain(code);
      }
      expect(markup).not.toMatch(/<script\b|https?:\/\/|\bon\w+\s*=|<iframe\b/i);
      expect(expected.source).toBe('Manually authored; never generated by TableFlow');
    },
  );

  it('ships an honest pending manual result template instead of fabricated passes', () => {
    const template = JSON.parse(readFileSync(resolve(root, 'result.example.json'), 'utf8'));
    expect(template.version).toBe('0.5.1');
    for (const field of ['testedAt', 'tester', 'edgeVersion', 'windowsVersion', 'excelVersion', 'privacyUrlValue']) {
      expect(template[field]).toBeNull();
    }
    for (const key of ['edgeStable', 'excelClipboard', 'excelCsv', 'scale100', 'scale125', 'scale150',
      'screenshotsReviewed', 'privacyUrl', 'publisherInfoReviewed']) {
      expect(template[key]).toBe('pending');
      expect(template.evidence[key]).toEqual([]);
    }
  });
});
