// Synthetic data and ordinary UI only. No extension mocks or remote assets.
const mode=document.body.dataset.mode;
const labels=['订单号','商品','城市','销售额','退款','日期'];
const names=['轻量保温杯','极简帆布包','桌面收纳盒','便携充电线','午后咖啡杯','云朵笔记本'];
function order(index){return [`DEMO-${String(index+1).padStart(5,'0')}`,names[index%names.length],['杭州','上海','深圳','南京'][index%4],`¥${(1299+index*37).toLocaleString('en-US')}.00`,index%7===0?'¥99.00':'—',`2026-10-${String(1+index%6).padStart(2,'0')}`];}
const body=document.createElement('div');
body.innerHTML=`<aside class="sidebar"><div class="brand">Table<b>Flow</b></div><small>合成业务演示 · 数据本地生成</small><nav aria-label="演示场景"><a href="index.html">订单明细</a><a href="pagination.html">分页示例</a><a href="virtual.html">可见窗口示例</a></nav><p class="side-note">演示数据不属于真实用户。<br>用扩展选择表格并核对范围，<br>再复制或导出。</p></aside><main class="workspace"><div class="breadcrumb">演示工作台 / 订单中心</div><header class="topline"><div><h1>订单明细</h1><p class="subtitle">先核对数据，再整理到你的工作表。</p></div><span class="local-tag">本地合成数据</span></header><section class="stats" aria-label="演示概览"><div class="stat"><span>演示订单数</span><strong>${mode==='virtual'?'10,000':mode==='pagination'?'120':'18'}<em>合成记录</em></strong></div><div class="stat"><span>数据列</span><strong>6<em>订单与商品明细</em></strong></div><div class="stat"><span>演示日期</span><strong>2026.10<em>固定数据</em></strong></div></section><section class="panel"><header class="panel-head"><div><h2>${mode==='pagination'?'本页订单':mode==='virtual'?'已加载的订单窗口':'订单列表'}</h2><p>${mode==='virtual'?'页面声明10000条，DOM仅保留一个可见窗口。':mode==='pagination'?'当前每页20条，共120条。扩展不会替你点击下一页。':'完整演示集，共18条合成订单。'}</p></div><span class="period">10月1日 — 10月6日</span></header><div id="table-area"></div><div id="pager" class="pager"></div></section><p class="notice">${mode==='pagination'?'此页为原生分页示例，通过声明总行数提示范围差异；专用“当前页”识别以已验证组件分页为准。不是假冒框架组件。':mode==='virtual'?'这是实际滚动复用DOM的本地演示。首次扫描并不包含全部10000条；导出前应查看扩展的范围提醒。':'TableFlow 读取当前页面的表格结构和可见文本。复制与导出由你主动发起；不上传网页内容。'}</p></main>`;
document.body.append(body);
document.querySelector(`nav a[href="${mode==='pagination'?'pagination':mode==='virtual'?'virtual':'index'}.html"]`).setAttribute('aria-current','page');
const area=document.querySelector('#table-area');
if(mode==='virtual'){
  const grid=document.createElement('div');grid.setAttribute('role','grid');grid.setAttribute('aria-label','订单可见窗口');grid.setAttribute('aria-rowcount','10001');grid.setAttribute('aria-colcount','6');
  const head=document.createElement('div');head.className='virtual-head';head.setAttribute('role','row');head.setAttribute('aria-rowindex','1');
  labels.forEach((label,index)=>{const cell=document.createElement('div');cell.textContent=label;cell.setAttribute('role','columnheader');cell.setAttribute('aria-colindex',String(index+1));head.append(cell);});grid.append(head);
  const scroller=document.createElement('div');scroller.className='virtual-scroll';const spacer=document.createElement('div');spacer.className='virtual-spacer';spacer.style.height=`${10000*44}px`;scroller.append(spacer);grid.append(scroller);area.append(grid);
  const slots=Array.from({length:16},()=>{const row=document.createElement('div');row.className='virtual-row';row.setAttribute('role','row');labels.forEach((_,index)=>{const cell=document.createElement('div');cell.setAttribute('role','gridcell');cell.setAttribute('aria-colindex',String(index+1));row.append(cell);});spacer.append(row);return row;});
  function render(){const start=Math.min(10000-slots.length,Math.floor(scroller.scrollTop/44));slots.forEach((row,slot)=>{const index=start+slot;row.style.top=`${index*44}px`;row.setAttribute('aria-rowindex',String(index+2));row.dataset.rowKey=`demo-${index}`;order(index).forEach((text,column)=>{row.children[column].textContent=text;});});}
  scroller.addEventListener('scroll',()=>requestAnimationFrame(render));render();document.querySelector('#pager').textContent='当前DOM窗口16条 · 共10000条合成记录';
}else{
  const wrap=document.createElement('div');wrap.className='table-wrap';const table=document.createElement('table');const caption=table.createCaption();caption.textContent=mode==='pagination'?'合成订单 · 分页数据':'合成订单 · 10月明细';if(mode==='pagination')table.setAttribute('aria-rowcount','121');
  const header=table.createTHead().insertRow();labels.forEach(label=>{const cell=document.createElement('th');cell.scope='col';cell.textContent=label;header.append(cell);});const tbody=table.createTBody();wrap.append(table);area.append(wrap);let page=1;
  function render(){tbody.replaceChildren();const count=mode==='pagination'?20:18;for(let offset=0;offset<count;offset++){const index=(page-1)*count+offset;const row=tbody.insertRow();row.setAttribute('aria-rowindex',String(index+2));order(index).forEach((text,column)=>{const cell=row.insertCell();cell.textContent=text;if(column===4)cell.className='refund';});}if(mode==='pagination'){const pager=document.querySelector('#pager');pager.replaceChildren();const info=document.createElement('span');info.textContent=`第${page} / 6页 · 当前20条 / 共120条`;const prev=document.createElement('button');prev.textContent='上一页';prev.disabled=page===1;prev.onclick=()=>{page--;render();};const next=document.createElement('button');next.textContent='下一页';next.disabled=page===6;next.onclick=()=>{page++;render();};pager.append(info,prev,next);}else document.querySelector('#pager').textContent='共18条 · 全部已显示';}
  render();
}
document.body.dataset.demoReady='true';
